# Generated by Django 5.2.11 on 2026-02-05 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='URL única de origen del video', max_length=500, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('transcript', models.TextField(help_text='Transcripción completa extraída')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('language_code', models.CharField(max_length=10)),
                ('sentiment', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tone', models.CharField(max_length=100)),
                ('key_points', models.JSONField(help_text='Lista de los 3 puntos clave en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de Video',
                'ordering': ['-created_at'],
            },
        ),
    ]
